apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sogebot.fullname" . }}
  labels:
  {{- include "sogebot.labels" . | nindent 4 }}
data:
  {{- if .Values.sogeBot.database.type }}
  TYPEORM_CONNECTION: {{ .Values.sogeBot.database.type }}
  {{- end }}
  {{- if .Values.sogeBot.database.host }}
  TYPEORM_HOST: {{ .Values.sogeBot.database.host }}
  {{- end }}
  {{- if .Values.sogeBot.database.port }}
  TYPEORM_PORT: {{ .Values.sogeBot.database.port }}
  {{- end }}
  {{- if .Values.sogeBot.database.type }}
  TYPEORM_DATABASE: {{ .Values.sogeBot.database.database }}
  {{- end }}
