{{- if .Values.persistence.enabled -}}
{{- $fullName := include "sogebot.fullname" . -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ $fullName }}-data"
  labels:
  {{- include "sogebot.labels" . | nindent 4 }}
  {{- with .Values.persistence.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
  {{ toYaml .Values.persistence.accessModes | indent 4 }}
  {{- if .Values.persistence.storageClass }}
  {{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
  {{- end }}
  {{- end }}
  resources:
    requests:
      storage: "{{ .Values.persistence.size }}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ $fullName }}-logs"
  labels:
  {{- include "sogebot.labels" . | nindent 4 }}
  {{- with .Values.persistence.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
  {{ toYaml .Values.persistence.accessModes | indent 4 }}
  {{- if .Values.persistence.storageClass }}
  {{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
  {{- end }}
  {{- end }}
  resources:
    requests:
      storage: "{{ .Values.persistence.size }}"
{{- end -}}
