{{- if and (ne .Values.sogeBot.database.type "better-sqlite3") (or (.Values.sogeBot.database.username) (.Values.sogeBot.database.password))}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sogebot.fullname" . }}
  labels:
  {{- include "sogebot.labels" . | nindent 4 }}
data:
  {{- if .Values.sogeBot.database.username }}
  TYPEORM_USERNAME: {{ .Values.sogeBot.database.username }}
  {{- end }}
  {{- if .Values.sogeBot.database.password }}
  TYPEORM_PASSWORD: {{ .Values.sogeBot.database.password }}
  {{- end }}
{{- end}}